### ISSUE TITLE
Demo URL

### ISSUE THREAD

**Issue by benmed00** [IndianGhost/liveSearch#3]
how to access the Live-Demo from the GitHub repo.

you may add an URL to your repo 👍 

https://www.jqueryscript.net/demo/Table-Live-Search-Plugin-jQuery/

**Comment by IndianGhost** [comment]
Done !

**Comment by benmed00** [comment]
you can upload your code at **[codepen](https://codepen.io/)**
it will be more useful for any changes or updates
